[dosbox]
machine=svga_s3
memsize=128

[cpu]
core=dynamic
cputype=pentium_ii
cycles=max

[autoexec]
IMGMOUNT C build/bananamind-dosboxx.img -ide 1m
IMGMOUNT D build/bananamind-dosboxx-nano-chat-q4.iso -t iso -ide 2m
BOOT C:
