#!/usr/bin/env python3
"""Convert the BananaMindOS SVG pointer to a compact two-color C bitmap."""

from __future__ import annotations

import argparse
import subprocess
import tempfile
from pathlib import Path

from PIL import Image


TRANSPARENT = 0
OUTLINE = 1
FILL = 2


def convert(source: Path, output: Path, width: int, height: int) -> None:
    with tempfile.TemporaryDirectory(prefix="bananamind-cursor-") as temp:
        raster = Path(temp) / "cursor.png"
        subprocess.run(
            ["rsvg-convert", "--output", str(raster), str(source)], check=True
        )
        image = Image.open(raster).convert("RGBA")
        bounds = image.getchannel("A").getbbox()
        if bounds is None:
            raise ValueError("cursor SVG rendered without visible pixels")
        image = image.crop(bounds)
        scale = min(width / image.width, height / image.height)
        scaled_width = max(1, round(image.width * scale))
        scaled_height = max(1, round(image.height * scale))
        image = image.resize((scaled_width, scaled_height), Image.Resampling.NEAREST)

        values: list[int] = []
        for y in range(height):
            for x in range(width):
                if x >= scaled_width or y >= scaled_height:
                    values.append(TRANSPARENT)
                    continue
                red, green, blue, alpha = image.getpixel((x, y))
                if alpha < 64:
                    values.append(TRANSPARENT)
                elif red + green + blue >= 3 * 128:
                    values.append(FILL)
                else:
                    values.append(OUTLINE)

    rows = []
    for y in range(height):
        row = values[y * width : (y + 1) * width]
        rows.append("    " + ", ".join(str(value) for value in row) + ",")

    output.write_text(
        "// Generated by tools/convert_cursor.py from assets/cursor.svg.\n"
        "#ifndef BANANAMIND_CURSOR_BITMAP_H\n"
        "#define BANANAMIND_CURSOR_BITMAP_H\n\n"
        "#include <stdint.h>\n\n"
        f"#define GUI_CURSOR_WIDTH {width}u\n"
        f"#define GUI_CURSOR_HEIGHT {height}u\n"
        "#define GUI_CURSOR_TRANSPARENT 0u\n"
        "#define GUI_CURSOR_OUTLINE 1u\n"
        "#define GUI_CURSOR_FILL 2u\n\n"
        "static const uint8_t gui_cursor_bitmap[GUI_CURSOR_WIDTH * GUI_CURSOR_HEIGHT] = {\n"
        + "\n".join(rows)
        + "\n};\n\n#endif\n",
        encoding="utf-8",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--width", type=int, default=18)
    parser.add_argument("--height", type=int, default=28)
    args = parser.parse_args()
    convert(args.source, args.output, args.width, args.height)


if __name__ == "__main__":
    main()
